### ISSUE TITLE
一点疑问

### ISSUE THREAD

**Issue by CoderLeonidas** [Resory/RYDatasource#2]
作者你好，市面上有很多给VC瘦身的方式，也就是像你这样做的，将代理对象指向一个中间人，由中间人来执行代理方法，以达到VC中不会有太多其他代理方法的目的。但是有一点疑问，这么做，对于真正减少VC代码行数，是否意义不大？代理方法中很多场景下都需要访问VC中的属性、变量、方法，比如你demo中的cell点击事件，这这些事件，还是不可避免的需要通过如block的方式传递给中间人去执行，那么这些代码还是会大量存在VC中。只是原先需要写在VC的代理方法里，现在是写在block的赋值。

**Comment by Resory** [comment]
我一直在用这个瘦身方式,VC总体而言会瘦100-150行代码,实际的cell的点击事件,cellSubview的点击事件,最终还是得VC通过代理处理.cell的数据处理还是得通过block放到了VC中做.实际上并没有多大的优化,反而在处理特殊情况,比如cell高度不定的时候会显得很麻烦.
总结就是:VC会少100-150行代码,但代价会多一个DataSource文件.虽然数据处理会麻烦点,但熟悉后我觉得还好,由于封装好了,整体可读性会强一点,做什么事,找什么文件.感觉会更高效点.实际上我最繁重的VC会接近千行代码.所以能瘦身100-150行代码,还是不错的.个人而言我是推荐使用的.但确实优化不大.所以是否使用还是得朋友你自己定夺~~

**Comment by CoderLeonidas** [comment]
哈哈，确实，具体问题具体分析，蟹蟹你回复~
